### ISSUE TITLE
Way to create pages based on FrontMatters in other files?

### ISSUE THREAD

**Issue by Sgoettschkes** [still-ex/still#175]
I'm wondering how one would go about implementing the generation of pages based on FrontMatters that are located within other files with Still.

As a real-world example, my Jekyll page has blog posts, each has a category defined. Jekyll does some magic and generates one page for each category, containing the list of blog posts with this category. I'm moving my blog and would like to keep these category pages.

My current idea would be to have a preprocessor for eex files (I'm using eex instead of slime), which adds all blog posts into a list (kinda like the collections for tags are built). From there, using a hook I could add a compiler that takes this list and creates category pages.

Is this the right approach? Is there something I'm missing?

**Comment by gabrielpoca** [comment]
Hello 👋
I think you're close, but that solution would only allow you to have one page for all categories. Unless you manually created a page for each category. This is because each input file can only generate one output file. So to have multiple "category" pages (one per category) on the output, you would need multiple "category" pages on the input. But, for reasons not related to having read your issue, I just finished the first step to allow for scenarios precisely like the one you just described 😎 https://github.com/still-ex/still/pull/176 The last step is to implement something like [11ty's pagination](https://www.11ty.dev/docs/pagination/) (it's not pagination as we usually think of it). Can you hold just for a bit? I'll finish it in a couple of days

**Comment by Sgoettschkes** [comment]
I see #176 is done. Does this mean it's usable? If it is, I'd volunteer to add some documentation as soon as I was able to understand the code as I couldn't find any docs in the PR?

**Comment by gabrielpoca** [comment]
Hey @Sgoettschkes sorry I was on vacation and then catching up with work. https://github.com/still-ex/still/pull/176/files is one of the core changes to allow for pages based on frontmatter. I'm working on it [here](https://github.com/still-ex/still/compare/gp-multiple-outputs?expand=1), would you have a look? I think functionality is working, and documentation is ongoing but I still need to write a better example and tests. I could use some feedback

**Comment by Sgoettschkes** [comment]
No worries, I didn't have time to work on this as well ;) I'll have a look and give feedback.
